apiVersion: v1
kind: Service
metadata:
  name: gitea-service
spec:
  selector:
    app: gitea
  type: LoadBalancer
  ports:
  - protocol: TCP
    targetPort: 3000
    port: 3456
    name: http
  - protocol: TCP
    targetPort: 22
    port: 22
    name: ssh
  