apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-demo-redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-redis
    spec:
      containers:
      - image: redis
        name: k8s-demo-redis
        volumeMounts:
        - mountPath: /data
          name: redis-data
      volumes:
      - name: redis-data
        emptyDir: {}
