apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-demo-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-db
    spec:
      containers:
      - image: postgres:9.4
        name: k8s-demo-db
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: db-data
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pgpassword
                key: POSTGRES_PASSWORD
      volumes:
      - name: db-data
        emptyDir: {}
